import type { Program } from '@/types/program';
import type { Workout } from '@/types/workout';

const ex = (name: string) => `/images/exercises/${name}`;

export const fallbackWorkouts: Workout[] = [
  { id:'1', slug:'pushups', name:'Push Ups', category:'Strength', level:'Beginner', duration:12, calories:90, image:ex('pushups.webp'), description:'Classic upper-body strength builder for chest, shoulders, triceps, and core stability.', muscles:['Chest','Shoulders','Triceps','Core'], instructions:['Set hands slightly wider than shoulders.','Brace your core and keep a straight body line.','Lower under control, then press strongly to the top.'] },
  { id:'2', slug:'squats', name:'Squats', category:'Strength', level:'Beginner', duration:15, calories:110, image:ex('squats.webp'), description:'Lower-body foundation movement for legs, hips, and athletic control.', muscles:['Quads','Glutes','Hamstrings'], instructions:['Stand tall with feet shoulder-width apart.','Sit hips back and down.','Drive through your heels to stand tall.'] },
  { id:'3', slug:'jumping-jacks', name:'Jumping Jacks', category:'Cardio', level:'Beginner', duration:10, calories:95, image:ex('jumpingjacks.webp'), description:'Fast full-body cardio movement for warming up and calorie burn.', muscles:['Full Body','Calves','Shoulders'], instructions:['Start standing tall.','Jump feet wide while arms move overhead.','Return softly and repeat with rhythm.'] },
  { id:'4', slug:'lunges', name:'Lunges', category:'Strength', level:'Intermediate', duration:14, calories:105, image:ex('lunges (1).webp'), description:'Single-leg strength builder for balance, knees, hips, and glutes.', muscles:['Glutes','Quads','Core'], instructions:['Step forward into a long stance.','Lower until both knees bend comfortably.','Push back to standing and alternate sides.'] },
  { id:'5', slug:'burpees', name:'Burpees', category:'HIIT', level:'Advanced', duration:12, calories:155, image:ex('burpees (1).webp'), altImage:ex('burpees1 (1).webp'), description:'High-output conditioning exercise combining squat, plank, push-up, and jump.', muscles:['Full Body','Chest','Legs','Core'], instructions:['Squat and place hands down.','Jump feet back to plank.','Return feet forward and jump explosively.'] },
  { id:'6', slug:'box-jumps', name:'Box Jumps', category:'HIIT', level:'Advanced', duration:13, calories:145, image:ex('boxjumps.webp'), altImage:ex('boxjumps1 (1).webp'), description:'Explosive power movement for legs, calves, and coordination.', muscles:['Glutes','Quads','Calves'], instructions:['Stand before a stable box.','Load hips back.','Jump and land softly with control.'] },
  { id:'7', slug:'plank', name:'Plank', category:'Core', level:'Beginner', duration:8, calories:45, image:ex('plank.webp'), description:'Core stability hold for abs, glutes, shoulders, and posture.', muscles:['Core','Glutes','Shoulders'], instructions:['Place elbows under shoulders.','Brace abs and glutes.','Hold a straight body line.'] },
  { id:'8', slug:'mountain-climbers', name:'Mountain Climbers', category:'HIIT', level:'Intermediate', duration:11, calories:125, image:ex('mountainclimbers (1).webp'), description:'Fast plank-based cardio for core, shoulders, and conditioning.', muscles:['Core','Shoulders','Hip Flexors'], instructions:['Start in high plank.','Drive one knee forward at a time.','Keep hips steady and move rhythmically.'] },
  { id:'9', slug:'crunches', name:'Crunches', category:'Core', level:'Beginner', duration:10, calories:65, image:ex('crunches (1).webp'), description:'Focused abdominal movement for core control and trunk strength.', muscles:['Abs','Core'], instructions:['Lie on your back with knees bent.','Lift shoulders using abs.','Lower slowly and repeat.'] },
  { id:'10', slug:'high-knees', name:'High Knees', category:'Cardio', level:'Intermediate', duration:9, calories:115, image:ex('highknees.webp'), description:'Fast cardio drill for hip flexors, core, and heart-rate elevation.', muscles:['Hip Flexors','Core','Calves'], instructions:['Run in place.','Drive knees toward waist height.','Keep arms active and posture tall.'] },
  { id:'11', slug:'glute-bridges', name:'Glute Bridges', category:'Strength', level:'Beginner', duration:11, calories:70, image:ex('glutebridges.webp'), description:'Posterior-chain exercise for glutes, hips, and lower-back support.', muscles:['Glutes','Hamstrings','Core'], instructions:['Lie down with knees bent.','Drive hips upward by squeezing glutes.','Pause, then lower with control.'] },
  { id:'12', slug:'leg-raises', name:'Leg Raises', category:'Core', level:'Intermediate', duration:10, calories:70, image:ex('legraises.webp'), description:'Lower-ab control drill for core strength and hip stability.', muscles:['Lower Abs','Hip Flexors'], instructions:['Lie flat and brace your core.','Raise legs under control.','Lower slowly without arching your back.'] },
  { id:'13', slug:'russian-twists', name:'Russian Twists', category:'Core', level:'Intermediate', duration:10, calories:75, image:ex('russiantwists.webp'), description:'Rotational core exercise for obliques and trunk control.', muscles:['Obliques','Abs'], instructions:['Sit with knees bent.','Lean back slightly.','Rotate side to side with control.'] },
  { id:'14', slug:'tricep-dips', name:'Tricep Dips', category:'Strength', level:'Intermediate', duration:10, calories:80, image:ex('tricepdips (1).webp'), description:'No-equipment arm exercise using a chair or stable edge.', muscles:['Triceps','Shoulders','Chest'], instructions:['Hands on edge behind you.','Lower elbows backward.','Press up without shrugging shoulders.'] },
  { id:'15', slug:'jump-squats', name:'Jump Squats', category:'HIIT', level:'Advanced', duration:10, calories:130, image:ex('jumpsquats.webp'), description:'Explosive lower-body conditioning drill for power and calorie burn.', muscles:['Quads','Glutes','Calves'], instructions:['Squat with control.','Jump vertically.','Land softly and reset.'] },
  { id:'16', slug:'downward-dog', name:'Downward Dog', category:'Mobility', level:'Beginner', duration:7, calories:25, image:ex('downwarddog.webp'), description:'Mobility posture for shoulders, hamstrings, calves, and spine.', muscles:['Hamstrings','Calves','Shoulders'], instructions:['Start on hands and knees.','Lift hips high.','Press chest gently toward thighs.'] },
  { id:'17', slug:'child-pose', name:'Child Pose', category:'Recovery', level:'Beginner', duration:6, calories:20, image:ex('childpose (1).webp'), description:'Recovery stretch for lower back, hips, and breathing reset.', muscles:['Back','Hips','Shoulders'], instructions:['Kneel and sit hips toward heels.','Reach arms forward.','Breathe slowly into your back.'] },
  { id:'18', slug:'butt-kicks', name:'Butt Kicks', category:'Cardio', level:'Beginner', duration:9, calories:85, image:ex('buttkicks (1).webp'), description:'Light cardio drill that warms hamstrings and improves running rhythm.', muscles:['Hamstrings','Calves'], instructions:['Jog in place.','Lift heels toward glutes.','Keep chest tall and arms moving naturally.'] },
  { id:'19', slug:'hip-flexor', name:'Hip Flexor Stretch', category:'Mobility', level:'Beginner', duration:7, calories:20, image:ex('hipflexor.webp'), description:'Mobility stretch for tight hips from sitting and training.', muscles:['Hip Flexors','Quads'], instructions:['Step into half-kneeling position.','Tuck pelvis gently.','Shift forward until stretch is felt.'] },
  { id:'20', slug:'pike-pushups', name:'Pike Push Ups', category:'Strength', level:'Advanced', duration:12, calories:95, image:ex('pikepushups.webp'), description:'Shoulder-focused push-up variation for upper-body strength.', muscles:['Shoulders','Triceps','Upper Chest'], instructions:['Start in an inverted V shape.','Lower head toward the floor.','Press back up through shoulders.'] },
  { id:'21', slug:'sprints', name:'Sprint Intervals', category:'Cardio', level:'Advanced', duration:16, calories:180, image:ex('sprints (1).webp'), description:'High-intensity intervals for conditioning, power, and fat loss.', muscles:['Full Body','Glutes','Hamstrings'], instructions:['Warm up first.','Sprint hard for short bursts.','Recover fully between rounds.'] },
];

export const fallbackPrograms: Program[] = [
  { id:'p1', slug:'starter-reset', title:'Starter Reset', duration:'14 days', level:'Beginner', focus:'Consistency, mobility, light strength', image:'/images/fit (1).webp', description:'A gentle but structured program to restart your fitness rhythm at home.', workouts:['jumping-jacks','squats','pushups','child-pose'] },
  { id:'p2', slug:'lean-burn', title:'Lean Burn', duration:'21 days', level:'Intermediate', focus:'Fat loss and cardio conditioning', image:'/images/image (1).jpg', description:'High-energy bodyweight circuits built for calorie burn without equipment.', workouts:['burpees','mountain-climbers','high-knees','sprints'] },
  { id:'p3', slug:'core-control', title:'Core Control', duration:'18 days', level:'Intermediate', focus:'Abs, posture, trunk strength', image:'/images/fit1 (1).webp', description:'Core-focused sessions combining stability, rotation, and lower-ab strength.', workouts:['plank','crunches','leg-raises','russian-twists'] },
  { id:'p4', slug:'power-athlete', title:'Power Athlete', duration:'28 days', level:'Advanced', focus:'Explosive power and full-body performance', image:'/images/Untitled (1).webp', description:'Advanced explosive home sessions for stronger legs, shoulders, and conditioning.', workouts:['box-jumps','jump-squats','pike-pushups','burpees'] },
];
